# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=release
endif
export config

PROJECTS := irc

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

irc: 
	@echo "==== Building irc ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f irc.make

clean:
	@${MAKE} --no-print-directory -C . -f irc.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   irc"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
